AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Llamafile on Lambda

Resources:
  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      Architectures:
        - arm64
      PackageType: Image
      ImageUri: llamafile-on-lambda:latest
      MemorySize: 10240
      Timeout: 600
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: RESPONSE_STREAM

Outputs:
  LambdaFunctionUrl:
    Description: Lambda Function URL
    Value: !GetAtt LambdaUrl.FunctionUrl
