AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Llamafile on Lambda

Globals:
  Function:
    Architectures: 
      - arm64

Resources:
  LlamafileFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: llamafile-on-lambda:latest
      MemorySize: 10240  # 10 GB of memory
      Timeout: 300  # 5 minutes, maximum is 15 minutes

Outputs:
  LlamafileFunctionArn:
    Description: "Llamafile on Lambda ARN"
    Value: !GetAtt LlamafileFunction.Arn
