#!/bin/sh
set -e

LLAMAFILE_PATH=${LLAMAFILE_PATH:-$(find "/opt/llamafile" -name "*.llamafile" -type f)}

echo "Starting llamafile ${LLAMAFILE_PATH}..."

$LLAMAFILE_PATH \
  --server \
  --fast \
  --threads "$(nproc)" \
  --gpu DISABLE \
  --no-warmup \
  --timeout 600 \
  --nobrowser \
  --log-disable \
  --host 127.0.0.1 \
  --port 8080
