#!/bin/sh
set -e

LLAMAFILE_PATH=${LLAMAFILE_PATH:-$(find "/opt/llamafile" -name "*.llamafile" -o -name "*.gguf" -type f)}

echo "Starting llamafile ${LLAMAFILE_PATH}..."

# Options that might make sense for you:
# 
# --path /nonexistent
# Avoid serving the non-API web interface.

# Option I am still testing out.
# 
# --fast \
# --nocompile \
# --threads 3 \
# --threads-batch 5 \
# --timeout 600

llamafile \
  --model $LLAMAFILE_PATH \
  --server \
  --fast \
  --gpu DISABLE \
  --nobrowser \
  --log-disable \
  --host 127.0.0.1 \
  --port 8080
